channels:
  - defaults
  - pytorch
dependencies:
  - pip=21.2.4
  - python=3.9.0
  - pytorch=1.10.0
  - torchvision=0.11.1
  - ignite=0.4.8
  - pip:
    - mypy==0.910
    - jupyter==1.0.0
    - numpy==1.21.2
    - notebook==6.4.4
    - flake8==4.0.1
    - scikit-learn==1.0
    - matplotlib==3.4.3
    - pytorch_lightning==1.4.9
    - lightning-bolts==0.4.0
    - yacs==0.1.8
    - pandas==1.3.4
    - pyod==0.9.4
    - papermill==2.3.3
    - scikit_image==0.18.3
    - pydicom==2.2.2
    - medmnist==2.0.2
    - gpytorch==1.6.0
    - tabulate==0.8.9
    - seaborn==0.11.2
    - laplace-torch==0.1a1
    - opencv-python==4.5.5.64
