seed: [10]
run_name: dropout_all_layers_autolr_paper
dataset: "RSNAPneumonia"
model_name: "resnet50"
n_classes: 2
training:
  p_dropout: 0.1
  num_epochs: 100
  batch_size: 32
  lr: 1e-4
  swag:
    swa_start: 50
    swa_lr: 0.01
    lr_init: 0.01
    num_epochs: 100
  duq:
    lr: 1e-2
    l_gradient_penalty: 0.1
    milestones: [25, 50]
augmentations:
  random_rotation: 30
  horizontal_flip: True
  expand_channels: True
  resize: 256
  random_crop: (0.8, 1)
  center_crop: 224
