seed: [11, 22, 33, 44, 55]
run_name: dropout_all_layers_autolr
dataset: "RSNAPneumonia"
model_name: "wideresnet50"
n_classes: 2
training:
  p_dropout: 0.1
  num_epochs: 100
  batch_size: 32
  lr: 1e-4
augmentations:
  random_rotation: 30
  horizontal_flip: True
  expand_channels: True
  resize: 256
  random_crop: (0.8, 1)
  center_crop: 224
