seed: [11, 22, 33, 44, 55]
run_name: "dropout_all_layers_autolr"
dataset: "OrganAMNIST"
model_name: "resnet18"
n_classes: 11
training:
  p_dropout: 0.1
  num_epochs: 100
  batch_size: 128
  lr: 1e-3
  swag:
    swa_start: 75
    swa_lr: 0.01 
    lr_init: 0.05
    num_epochs: 100
  duq:
    lr: 0.01
    l_gradient_penalty: 0.5
    milestones: [50, 75]
augmentations:
  expand_channels: True



