name: Project Automation

on:
  issues:
    types:
      - assigned
  pull_request:
    types:
      - opened
      - closed

jobs:
  move-to-in-progress:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Move assigned issue to "In Progress"
        uses: actions/github-script@v6
        with:
          script: |
            const columnName = "In Progress"; // Name of the column for "In Progress"

            // Dynamically determine repository context
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            // Project ID
            const projectId = 2; // Project ID extracted from your URL

            // Get project columns
            const columns = await github.rest.projects.listColumns({
              project_id: projectId,
              headers: { accept: "application/vnd.github.inertia-preview+json" }
            });

            const column = columns.data.find(col => col.name === columnName);
            if (!column) throw new Error(`Column ${columnName} not found`);

            const card = await github.rest.projects.createCard({
              column_id: column.id,
              content_id: context.payload.issue.node_id,
              content_type: "Issue"
            });

  move-to-in-review:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: Move linked issue to "In Review"
        uses: actions/github-script@v6
        with:
          script: |
            const columnName = "In Review"; // Name of the column for "In Review"

            // Dynamically determine repository context
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            // Project ID
            const projectId = 2; // Project ID extracted from your URL

            // Get project columns
            const columns = await github.rest.projects.listColumns({
              project_id: projectId,
              headers: { accept: "application/vnd.github.inertia-preview+json" }
            });

            const column = columns.data.find(col => col.name === columnName);
            if (!column) throw new Error(`Column ${columnName} not found`);

            const linkedIssues = context.payload.pull_request.body.match(/#(\d+)/g);
            if (linkedIssues) {
              for (const issueNumber of linkedIssues) {
                const issue = await github.rest.issues.get({
                  owner: repoOwner,
                  repo: repoName,
                  issue_number: issueNumber.replace("#", "")
                });

                await github.rest.projects.createCard({
                  column_id: column.id,
                  content_id: issue.data.node_id,
                  content_type: "Issue"
                });
              }
            }

  move-to-done:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Move linked issue to "Done"
        uses: actions/github-script@v6
        with:
          script: |
            const columnName = "Done"; // Name of the column for "Done"

            // Dynamically determine repository context
            const repoOwner = context.repo.owner;
            const repoName = context.repo.repo;

            // Project ID
            const projectId = 2; // Project ID extracted from your URL

            // Get project columns
            const columns = await github.rest.projects.listColumns({
              project_id: projectId,
              headers: { accept: "application/vnd.github.inertia-preview+json" }
            });

            const column = columns.data.find(col => col.name === columnName);
            if (!column) throw new Error(`Column ${columnName} not found`);

            const linkedIssues = context.payload.pull_request.body.match(/#(\d+)/g);
            if (linkedIssues) {
              for (const issueNumber of linkedIssues) {
                const issue = await github.rest.issues.get({
                  owner: repoOwner,
                  repo: repoName,
                  issue_number: issueNumber.replace("#", "")
                });

                await github.rest.projects.createCard({
                  column_id: column.id,
                  content_id: issue.data.node_id,
                  content_type: "Issue"
                });
              }
            }
